import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "fr" | "es" | "pt" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.dashboard": "Dashboard",
    "nav.signIn": "Sign In",
    "nav.myDashboard": "My Dashboard",
    "nav.myWishlist": "My Wishlist",
    "nav.myCart": "My Cart",
    "nav.signOut": "Sign Out",

    // Home
    "home.badge": "New Collection Available",
    "home.heroTitle1": "Discover Your",
    "home.heroTitle2": "Perfect Style",
    "home.heroSubtitle": "Shop the latest trends in fashion, electronics, and accessories. Premium quality products curated just for you.",
    "home.shopNow": "Shop Now",
    "home.learnMore": "Learn More",
    "home.reviews": "4.9/5 from 2,000+ reviews",
    "home.freeShippingBadge": "Free shipping on $50+",
    "home.freeShipping": "Free Shipping",
    "home.freeShippingDesc": "On orders over $50",
    "home.securePayment": "Secure Payment",
    "home.securePaymentDesc": "100% protected transactions",
    "home.support": "24/7 Support",
    "home.supportDesc": "Dedicated customer service",
    "home.trending": "Trending Now",
    "home.featured": "Featured Products",
    "home.featuredDesc": "Handpicked selection of our best sellers loved by thousands",
    "home.viewAll": "View All Products",
    "home.ctaTitle": "Ready to Start Shopping?",
    "home.ctaSubtitle": "Join thousands of happy customers and discover amazing deals every day",
    "home.browseCollection": "Browse Collection",

    // Shop
    "shop.title": "Shop All Products",
    "shop.subtitle": "Browse our complete collection of premium products",
    "shop.search": "Search products...",
    "shop.allCategories": "All Categories",
    "shop.newest": "Newest",
    "shop.priceLow": "Price: Low to High",
    "shop.priceHigh": "Price: High to Low",
    "shop.popular": "Popular",
    "shop.highestRated": "Highest Rated",
    "shop.deals": "Limited Time Deals",
    "shop.onSale": "On Sale",
    "shop.inStock": "In Stock Only",
    "shop.minRating": "Minimum Rating",
    "shop.allRatings": "All ratings",
    "shop.priceRange": "Price Range",
    "shop.showing": "Showing",
    "shop.of": "of",
    "shop.products": "products",
    "shop.noProducts": "No products found",
    "shop.noProductsDesc": "Try adjusting your filters or search query",

    // Contact
    "contact.title": "Get in Touch",
    "contact.subtitle": "Have a question? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    "contact.sendMessage": "Send us a message",
    "contact.messageSent": "Message Sent!",
    "contact.messageSentDesc": "Thank you for reaching out. We'll get back to you soon.",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.namePlaceholder": "Your name",
    "contact.emailPlaceholder": "your@email.com",
    "contact.subjectPlaceholder": "How can we help?",
    "contact.messagePlaceholder": "Tell us more about your inquiry...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.emailUs": "Email Us",
    "contact.callUs": "Call Us",
    "contact.visitUs": "Visit Us",
    "contact.hours": "Sun-Sat: 9AM - 6PM",

    // Cart & Checkout
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptyDesc": "Looks like you haven't added any products yet",
    "cart.browse": "Browse Products",
    "cart.clearAll": "Clear All",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping calculated at checkout",
    "cart.checkout": "Proceed to Checkout",
    "cart.continueShopping": "Continue Shopping",
    "cart.selectItems": "Select Items to Pay For",
    "cart.selectAll": "Select All",
    "cart.deselectAll": "Deselect All",
    "cart.items": "items",
    "cart.selected": "selected",
    "cart.continuePayment": "Continue to Payment",
    "cart.backToCart": "Back to Cart",

    // Checkout
    "checkout.choosePayment": "Choose Payment Method",
    "checkout.selectCurrency": "Select Payment Currency",
    "checkout.currencyRequired": "Please select a currency to continue",
    "checkout.fiatCurrency": "Fiat Currency",
    "checkout.cryptocurrency": "Cryptocurrency",
    "checkout.bankTransfer": "Bank Transfer",
    "checkout.bankTransferDesc": "Direct bank deposit",
    "checkout.cryptoDesc": "USDT (BEP20)",
    "checkout.stablecoin": "Stablecoin payment",
    "checkout.paymentDetails": "Payment Details",
    "checkout.transactionRef": "Transaction Reference / Hash",
    "checkout.paymentDate": "Payment Date",
    "checkout.senderName": "Sender Name",
    "checkout.senderNamePlaceholder": "Name on the bank account or wallet",
    "checkout.additionalNotes": "Additional Notes (Optional)",
    "checkout.notesPlaceholder": "Any additional information about your payment...",
    "checkout.proofRequired": "Payment Proof",
    "checkout.uploadProof": "Click to upload payment proof",
    "checkout.uploadFormats": "JPG, PNG, WebP, or PDF (max 5MB)",
    "checkout.orderSummary": "Order Summary",
    "checkout.total": "Total",
    "checkout.submitOrder": "Submit Order",
    "checkout.uploading": "Uploading...",
    "checkout.processing": "Processing order...",
    "checkout.submitting": "Submitting...",
    "checkout.wait": "Please wait while we process your order...",
    "checkout.orderSubmitted": "Order Submitted!",
    "checkout.orderPlaced": "has been placed.",
    "checkout.verifyNotice": "We'll notify you once your payment is verified.",
    "checkout.goToDashboard": "Go to Dashboard",
    "checkout.viewOrder": "View Order Details",
    "checkout.reversePurchase": "Reverse Purchase (within 24h)",

    // Footer
    "footer.newsletter": "Subscribe to Our Newsletter",
    "footer.newsletterDesc": "Get exclusive offers, new product alerts, and style tips delivered to your inbox.",
    "footer.emailPlaceholder": "Enter your email",
    "footer.subscribe": "Subscribe",
    "footer.subscribing": "Subscribing...",
    "footer.quickLinks": "Quick Links",
    "footer.customerService": "Customer Service",
    "footer.contactUs": "Contact Us",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.shippingPolicy": "Shipping Policy",
    "footer.description": "Your premier destination for trendy fashion, electronics, and lifestyle products. Quality guaranteed, style delivered.",

    // General
    "general.all": "All",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.shop": "Boutique",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.dashboard": "Tableau de bord",
    "nav.signIn": "Se connecter",
    "nav.myDashboard": "Mon tableau de bord",
    "nav.myWishlist": "Ma liste de souhaits",
    "nav.myCart": "Mon panier",
    "nav.signOut": "Se déconnecter",
    "home.badge": "Nouvelle collection disponible",
    "home.heroTitle1": "Découvrez Votre",
    "home.heroTitle2": "Style Parfait",
    "home.heroSubtitle": "Achetez les dernières tendances en mode, électronique et accessoires. Des produits de qualité premium sélectionnés pour vous.",
    "home.shopNow": "Acheter maintenant",
    "home.learnMore": "En savoir plus",
    "home.reviews": "4.9/5 de plus de 2 000 avis",
    "home.freeShippingBadge": "Livraison gratuite dès 50$",
    "home.freeShipping": "Livraison gratuite",
    "home.freeShippingDesc": "Sur les commandes de plus de 50$",
    "home.securePayment": "Paiement sécurisé",
    "home.securePaymentDesc": "Transactions 100% protégées",
    "home.support": "Support 24/7",
    "home.supportDesc": "Service client dédié",
    "home.trending": "Tendances",
    "home.featured": "Produits en vedette",
    "home.featuredDesc": "Sélection triée sur le volet de nos meilleures ventes",
    "home.viewAll": "Voir tous les produits",
    "home.ctaTitle": "Prêt à commencer vos achats ?",
    "home.ctaSubtitle": "Rejoignez des milliers de clients satisfaits",
    "home.browseCollection": "Parcourir la collection",
    "shop.title": "Tous les produits",
    "shop.subtitle": "Parcourez notre collection complète de produits premium",
    "shop.search": "Rechercher des produits...",
    "shop.allCategories": "Toutes les catégories",
    "shop.newest": "Plus récent",
    "shop.priceLow": "Prix : croissant",
    "shop.priceHigh": "Prix : décroissant",
    "shop.popular": "Populaire",
    "shop.highestRated": "Mieux noté",
    "shop.deals": "Offres limitées",
    "shop.onSale": "En solde",
    "shop.inStock": "En stock uniquement",
    "shop.minRating": "Note minimale",
    "shop.allRatings": "Toutes les notes",
    "shop.priceRange": "Gamme de prix",
    "shop.showing": "Affichage de",
    "shop.of": "sur",
    "shop.products": "produits",
    "shop.noProducts": "Aucun produit trouvé",
    "shop.noProductsDesc": "Essayez d'ajuster vos filtres",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Vous avez une question ? Envoyez-nous un message et nous vous répondrons dès que possible.",
    "contact.sendMessage": "Envoyez-nous un message",
    "contact.messageSent": "Message envoyé !",
    "contact.messageSentDesc": "Merci de nous avoir contactés. Nous vous répondrons bientôt.",
    "contact.name": "Nom",
    "contact.email": "E-mail",
    "contact.subject": "Sujet",
    "contact.message": "Message",
    "contact.namePlaceholder": "Votre nom",
    "contact.emailPlaceholder": "votre@email.com",
    "contact.subjectPlaceholder": "Comment pouvons-nous vous aider ?",
    "contact.messagePlaceholder": "Dites-nous en plus sur votre demande...",
    "contact.send": "Envoyer le message",
    "contact.sending": "Envoi en cours...",
    "contact.emailUs": "Écrivez-nous",
    "contact.callUs": "Appelez-nous",
    "contact.visitUs": "Rendez-nous visite",
    "contact.hours": "Dim-Sam : 9h - 18h",
    "cart.title": "Panier",
    "cart.empty": "Votre panier est vide",
    "cart.emptyDesc": "Il semble que vous n'ayez encore ajouté aucun produit",
    "cart.browse": "Parcourir les produits",
    "cart.clearAll": "Tout supprimer",
    "cart.subtotal": "Sous-total",
    "cart.shipping": "Frais de port calculés au paiement",
    "cart.checkout": "Passer à la caisse",
    "cart.continueShopping": "Continuer les achats",
    "cart.selectItems": "Sélectionner les articles à payer",
    "cart.selectAll": "Tout sélectionner",
    "cart.deselectAll": "Tout désélectionner",
    "cart.items": "articles",
    "cart.selected": "sélectionné(s)",
    "cart.continuePayment": "Continuer vers le paiement",
    "cart.backToCart": "Retour au panier",
    "checkout.choosePayment": "Choisir le mode de paiement",
    "checkout.selectCurrency": "Sélectionner la devise",
    "checkout.currencyRequired": "Veuillez sélectionner une devise pour continuer",
    "checkout.fiatCurrency": "Devise fiduciaire",
    "checkout.cryptocurrency": "Cryptomonnaie",
    "checkout.bankTransfer": "Virement bancaire",
    "checkout.bankTransferDesc": "Dépôt bancaire direct",
    "checkout.cryptoDesc": "USDT (BEP20)",
    "checkout.stablecoin": "Paiement par stablecoin",
    "checkout.paymentDetails": "Détails du paiement",
    "checkout.transactionRef": "Référence de transaction / Hash",
    "checkout.paymentDate": "Date de paiement",
    "checkout.senderName": "Nom de l'expéditeur",
    "checkout.senderNamePlaceholder": "Nom sur le compte bancaire ou le portefeuille",
    "checkout.additionalNotes": "Notes supplémentaires (Optionnel)",
    "checkout.notesPlaceholder": "Toute information supplémentaire sur votre paiement...",
    "checkout.proofRequired": "Preuve de paiement",
    "checkout.uploadProof": "Cliquez pour télécharger la preuve de paiement",
    "checkout.uploadFormats": "JPG, PNG, WebP, ou PDF (max 5 Mo)",
    "checkout.orderSummary": "Résumé de la commande",
    "checkout.total": "Total",
    "checkout.submitOrder": "Soumettre la commande",
    "checkout.uploading": "Téléchargement...",
    "checkout.processing": "Traitement de la commande...",
    "checkout.submitting": "Envoi en cours...",
    "checkout.wait": "Veuillez patienter pendant que nous traitons votre commande...",
    "checkout.orderSubmitted": "Commande soumise !",
    "checkout.orderPlaced": "a été passée.",
    "checkout.verifyNotice": "Nous vous notifierons une fois votre paiement vérifié.",
    "checkout.goToDashboard": "Aller au tableau de bord",
    "checkout.viewOrder": "Voir les détails",
    "checkout.reversePurchase": "Annuler l'achat (dans les 24h)",
    "footer.newsletter": "Abonnez-vous à notre newsletter",
    "footer.newsletterDesc": "Recevez des offres exclusives et des alertes de nouveaux produits.",
    "footer.emailPlaceholder": "Entrez votre e-mail",
    "footer.subscribe": "S'abonner",
    "footer.subscribing": "Abonnement...",
    "footer.quickLinks": "Liens rapides",
    "footer.customerService": "Service client",
    "footer.contactUs": "Contactez-nous",
    "footer.rights": "Tous droits réservés.",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.shippingPolicy": "Politique de livraison",
    "footer.description": "Votre destination premium pour la mode, l'électronique et les produits lifestyle.",
    "general.all": "Tous",
  },
  es: {
    "nav.home": "Inicio",
    "nav.shop": "Tienda",
    "nav.about": "Acerca de",
    "nav.contact": "Contacto",
    "nav.dashboard": "Panel",
    "nav.signIn": "Iniciar sesión",
    "nav.myDashboard": "Mi panel",
    "nav.myWishlist": "Mi lista de deseos",
    "nav.myCart": "Mi carrito",
    "nav.signOut": "Cerrar sesión",
    "home.badge": "Nueva colección disponible",
    "home.heroTitle1": "Descubre Tu",
    "home.heroTitle2": "Estilo Perfecto",
    "home.heroSubtitle": "Compra las últimas tendencias en moda, electrónica y accesorios. Productos de calidad premium seleccionados para ti.",
    "home.shopNow": "Comprar ahora",
    "home.learnMore": "Saber más",
    "home.reviews": "4.9/5 de más de 2,000 reseñas",
    "home.freeShippingBadge": "Envío gratis en compras de $50+",
    "home.freeShipping": "Envío gratuito",
    "home.freeShippingDesc": "En pedidos superiores a $50",
    "home.securePayment": "Pago seguro",
    "home.securePaymentDesc": "Transacciones 100% protegidas",
    "home.support": "Soporte 24/7",
    "home.supportDesc": "Servicio al cliente dedicado",
    "home.trending": "Tendencias",
    "home.featured": "Productos destacados",
    "home.featuredDesc": "Selección de nuestros más vendidos",
    "home.viewAll": "Ver todos los productos",
    "home.ctaTitle": "¿Listo para comenzar a comprar?",
    "home.ctaSubtitle": "Únete a miles de clientes satisfechos",
    "home.browseCollection": "Explorar colección",
    "shop.title": "Todos los productos",
    "shop.subtitle": "Explora nuestra colección completa de productos premium",
    "shop.search": "Buscar productos...",
    "shop.allCategories": "Todas las categorías",
    "shop.newest": "Más reciente",
    "shop.priceLow": "Precio: menor a mayor",
    "shop.priceHigh": "Precio: mayor a menor",
    "shop.popular": "Popular",
    "shop.highestRated": "Mejor valorado",
    "shop.deals": "Ofertas limitadas",
    "shop.onSale": "En oferta",
    "shop.inStock": "Solo en stock",
    "shop.minRating": "Calificación mínima",
    "shop.allRatings": "Todas las calificaciones",
    "shop.priceRange": "Rango de precio",
    "shop.showing": "Mostrando",
    "shop.of": "de",
    "shop.products": "productos",
    "shop.noProducts": "No se encontraron productos",
    "shop.noProductsDesc": "Intenta ajustar tus filtros",
    "contact.title": "Contáctanos",
    "contact.subtitle": "¿Tienes una pregunta? Envíanos un mensaje y te responderemos lo antes posible.",
    "contact.sendMessage": "Envíanos un mensaje",
    "contact.messageSent": "¡Mensaje enviado!",
    "contact.messageSentDesc": "Gracias por contactarnos. Te responderemos pronto.",
    "contact.name": "Nombre",
    "contact.email": "Correo electrónico",
    "contact.subject": "Asunto",
    "contact.message": "Mensaje",
    "contact.namePlaceholder": "Tu nombre",
    "contact.emailPlaceholder": "tu@correo.com",
    "contact.subjectPlaceholder": "¿Cómo podemos ayudarte?",
    "contact.messagePlaceholder": "Cuéntanos más sobre tu consulta...",
    "contact.send": "Enviar mensaje",
    "contact.sending": "Enviando...",
    "contact.emailUs": "Escríbenos",
    "contact.callUs": "Llámanos",
    "contact.visitUs": "Visítanos",
    "contact.hours": "Dom-Sáb: 9AM - 6PM",
    "cart.title": "Carrito",
    "cart.empty": "Tu carrito está vacío",
    "cart.emptyDesc": "Parece que aún no has añadido ningún producto",
    "cart.browse": "Explorar productos",
    "cart.clearAll": "Vaciar todo",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Envío calculado al pagar",
    "cart.checkout": "Ir a pagar",
    "cart.continueShopping": "Seguir comprando",
    "cart.selectItems": "Seleccionar artículos a pagar",
    "cart.selectAll": "Seleccionar todo",
    "cart.deselectAll": "Deseleccionar todo",
    "cart.items": "artículos",
    "cart.selected": "seleccionado(s)",
    "cart.continuePayment": "Continuar al pago",
    "cart.backToCart": "Volver al carrito",
    "checkout.choosePayment": "Elegir método de pago",
    "checkout.selectCurrency": "Seleccionar moneda de pago",
    "checkout.currencyRequired": "Por favor selecciona una moneda para continuar",
    "checkout.fiatCurrency": "Moneda fiduciaria",
    "checkout.cryptocurrency": "Criptomoneda",
    "checkout.bankTransfer": "Transferencia bancaria",
    "checkout.bankTransferDesc": "Depósito bancario directo",
    "checkout.cryptoDesc": "USDT (BEP20)",
    "checkout.stablecoin": "Pago con stablecoin",
    "checkout.paymentDetails": "Detalles del pago",
    "checkout.transactionRef": "Referencia de transacción / Hash",
    "checkout.paymentDate": "Fecha de pago",
    "checkout.senderName": "Nombre del remitente",
    "checkout.senderNamePlaceholder": "Nombre en la cuenta bancaria o billetera",
    "checkout.additionalNotes": "Notas adicionales (Opcional)",
    "checkout.notesPlaceholder": "Información adicional sobre tu pago...",
    "checkout.proofRequired": "Comprobante de pago",
    "checkout.uploadProof": "Clic para subir comprobante de pago",
    "checkout.uploadFormats": "JPG, PNG, WebP o PDF (máx 5MB)",
    "checkout.orderSummary": "Resumen del pedido",
    "checkout.total": "Total",
    "checkout.submitOrder": "Enviar pedido",
    "checkout.uploading": "Subiendo...",
    "checkout.processing": "Procesando pedido...",
    "checkout.submitting": "Enviando...",
    "checkout.wait": "Por favor espera mientras procesamos tu pedido...",
    "checkout.orderSubmitted": "¡Pedido enviado!",
    "checkout.orderPlaced": "ha sido realizado.",
    "checkout.verifyNotice": "Te notificaremos cuando tu pago sea verificado.",
    "checkout.goToDashboard": "Ir al panel",
    "checkout.viewOrder": "Ver detalles del pedido",
    "checkout.reversePurchase": "Revertir compra (dentro de 24h)",
    "footer.newsletter": "Suscríbete a nuestro boletín",
    "footer.newsletterDesc": "Recibe ofertas exclusivas y alertas de nuevos productos.",
    "footer.emailPlaceholder": "Ingresa tu correo",
    "footer.subscribe": "Suscribirse",
    "footer.subscribing": "Suscribiendo...",
    "footer.quickLinks": "Enlaces rápidos",
    "footer.customerService": "Servicio al cliente",
    "footer.contactUs": "Contáctanos",
    "footer.rights": "Todos los derechos reservados.",
    "footer.privacy": "Política de privacidad",
    "footer.terms": "Términos de servicio",
    "footer.shippingPolicy": "Política de envío",
    "footer.description": "Tu destino premium para moda, electrónica y productos de estilo de vida.",
    "general.all": "Todos",
  },
  pt: {
    "nav.home": "Início",
    "nav.shop": "Loja",
    "nav.about": "Sobre",
    "nav.contact": "Contato",
    "nav.dashboard": "Painel",
    "nav.signIn": "Entrar",
    "nav.myDashboard": "Meu painel",
    "nav.myWishlist": "Minha lista de desejos",
    "nav.myCart": "Meu carrinho",
    "nav.signOut": "Sair",
    "home.badge": "Nova coleção disponível",
    "home.heroTitle1": "Descubra Seu",
    "home.heroTitle2": "Estilo Perfeito",
    "home.heroSubtitle": "Compre as últimas tendências em moda, eletrônicos e acessórios. Produtos premium selecionados para você.",
    "home.shopNow": "Comprar agora",
    "home.learnMore": "Saiba mais",
    "home.reviews": "4.9/5 de mais de 2.000 avaliações",
    "home.freeShippingBadge": "Frete grátis acima de $50",
    "home.freeShipping": "Frete grátis",
    "home.freeShippingDesc": "Em pedidos acima de $50",
    "home.securePayment": "Pagamento seguro",
    "home.securePaymentDesc": "Transações 100% protegidas",
    "home.support": "Suporte 24/7",
    "home.supportDesc": "Atendimento dedicado",
    "home.trending": "Em alta",
    "home.featured": "Produtos em destaque",
    "home.featuredDesc": "Seleção dos nossos mais vendidos",
    "home.viewAll": "Ver todos os produtos",
    "home.ctaTitle": "Pronto para começar a comprar?",
    "home.ctaSubtitle": "Junte-se a milhares de clientes satisfeitos",
    "home.browseCollection": "Explorar coleção",
    "shop.title": "Todos os produtos",
    "shop.subtitle": "Explore nossa coleção completa de produtos premium",
    "shop.search": "Buscar produtos...",
    "shop.allCategories": "Todas as categorias",
    "shop.newest": "Mais recente",
    "shop.priceLow": "Preço: menor para maior",
    "shop.priceHigh": "Preço: maior para menor",
    "shop.popular": "Popular",
    "shop.highestRated": "Melhor avaliado",
    "shop.deals": "Ofertas limitadas",
    "shop.onSale": "Em promoção",
    "shop.inStock": "Apenas em estoque",
    "shop.minRating": "Avaliação mínima",
    "shop.allRatings": "Todas as avaliações",
    "shop.priceRange": "Faixa de preço",
    "shop.showing": "Exibindo",
    "shop.of": "de",
    "shop.products": "produtos",
    "shop.noProducts": "Nenhum produto encontrado",
    "shop.noProductsDesc": "Tente ajustar seus filtros",
    "contact.title": "Entre em contato",
    "contact.subtitle": "Tem uma pergunta? Envie-nos uma mensagem e responderemos o mais breve possível.",
    "contact.sendMessage": "Envie-nos uma mensagem",
    "contact.messageSent": "Mensagem enviada!",
    "contact.messageSentDesc": "Obrigado por entrar em contato. Responderemos em breve.",
    "contact.name": "Nome",
    "contact.email": "E-mail",
    "contact.subject": "Assunto",
    "contact.message": "Mensagem",
    "contact.namePlaceholder": "Seu nome",
    "contact.emailPlaceholder": "seu@email.com",
    "contact.subjectPlaceholder": "Como podemos ajudar?",
    "contact.messagePlaceholder": "Conte-nos mais sobre sua dúvida...",
    "contact.send": "Enviar mensagem",
    "contact.sending": "Enviando...",
    "contact.emailUs": "Nos envie um e-mail",
    "contact.callUs": "Ligue para nós",
    "contact.visitUs": "Visite-nos",
    "contact.hours": "Dom-Sáb: 9h - 18h",
    "cart.title": "Carrinho",
    "cart.empty": "Seu carrinho está vazio",
    "cart.emptyDesc": "Parece que você ainda não adicionou nenhum produto",
    "cart.browse": "Explorar produtos",
    "cart.clearAll": "Limpar tudo",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Frete calculado no checkout",
    "cart.checkout": "Finalizar compra",
    "cart.continueShopping": "Continuar comprando",
    "cart.selectItems": "Selecionar itens para pagar",
    "cart.selectAll": "Selecionar tudo",
    "cart.deselectAll": "Desmarcar tudo",
    "cart.items": "itens",
    "cart.selected": "selecionado(s)",
    "cart.continuePayment": "Continuar para pagamento",
    "cart.backToCart": "Voltar ao carrinho",
    "checkout.choosePayment": "Escolher método de pagamento",
    "checkout.selectCurrency": "Selecionar moeda de pagamento",
    "checkout.currencyRequired": "Selecione uma moeda para continuar",
    "checkout.fiatCurrency": "Moeda fiduciária",
    "checkout.cryptocurrency": "Criptomoeda",
    "checkout.bankTransfer": "Transferência bancária",
    "checkout.bankTransferDesc": "Depósito bancário direto",
    "checkout.cryptoDesc": "USDT (BEP20)",
    "checkout.stablecoin": "Pagamento com stablecoin",
    "checkout.paymentDetails": "Detalhes do pagamento",
    "checkout.transactionRef": "Referência da transação / Hash",
    "checkout.paymentDate": "Data do pagamento",
    "checkout.senderName": "Nome do remetente",
    "checkout.senderNamePlaceholder": "Nome na conta bancária ou carteira",
    "checkout.additionalNotes": "Notas adicionais (Opcional)",
    "checkout.notesPlaceholder": "Informações adicionais sobre seu pagamento...",
    "checkout.proofRequired": "Comprovante de pagamento",
    "checkout.uploadProof": "Clique para enviar comprovante",
    "checkout.uploadFormats": "JPG, PNG, WebP ou PDF (máx 5MB)",
    "checkout.orderSummary": "Resumo do pedido",
    "checkout.total": "Total",
    "checkout.submitOrder": "Enviar pedido",
    "checkout.uploading": "Enviando...",
    "checkout.processing": "Processando pedido...",
    "checkout.submitting": "Enviando...",
    "checkout.wait": "Aguarde enquanto processamos seu pedido...",
    "checkout.orderSubmitted": "Pedido enviado!",
    "checkout.orderPlaced": "foi realizado.",
    "checkout.verifyNotice": "Notificaremos quando seu pagamento for verificado.",
    "checkout.goToDashboard": "Ir ao painel",
    "checkout.viewOrder": "Ver detalhes do pedido",
    "checkout.reversePurchase": "Reverter compra (dentro de 24h)",
    "footer.newsletter": "Assine nossa newsletter",
    "footer.newsletterDesc": "Receba ofertas exclusivas e alertas de novos produtos.",
    "footer.emailPlaceholder": "Digite seu e-mail",
    "footer.subscribe": "Assinar",
    "footer.subscribing": "Assinando...",
    "footer.quickLinks": "Links rápidos",
    "footer.customerService": "Atendimento ao cliente",
    "footer.contactUs": "Contato",
    "footer.rights": "Todos os direitos reservados.",
    "footer.privacy": "Política de privacidade",
    "footer.terms": "Termos de serviço",
    "footer.shippingPolicy": "Política de envio",
    "footer.description": "Seu destino premium para moda, eletrônicos e produtos de lifestyle.",
    "general.all": "Todos",
  },
  zh: {
    "nav.home": "首页",
    "nav.shop": "商店",
    "nav.about": "关于我们",
    "nav.contact": "联系",
    "nav.dashboard": "控制面板",
    "nav.signIn": "登录",
    "nav.myDashboard": "我的面板",
    "nav.myWishlist": "我的收藏",
    "nav.myCart": "我的购物车",
    "nav.signOut": "退出",
    "home.badge": "新品上市",
    "home.heroTitle1": "发现你的",
    "home.heroTitle2": "完美风格",
    "home.heroSubtitle": "购买最新时尚、电子产品和配饰。为您精选的优质产品。",
    "home.shopNow": "立即购买",
    "home.learnMore": "了解更多",
    "home.reviews": "4.9/5 来自2,000+评价",
    "home.freeShippingBadge": "$50以上免运费",
    "home.freeShipping": "免费配送",
    "home.freeShippingDesc": "满$50免运费",
    "home.securePayment": "安全支付",
    "home.securePaymentDesc": "100%安全交易",
    "home.support": "24/7客服",
    "home.supportDesc": "专业客户服务",
    "home.trending": "热门趋势",
    "home.featured": "精选产品",
    "home.featuredDesc": "精心挑选的畅销商品",
    "home.viewAll": "查看所有产品",
    "home.ctaTitle": "准备好开始购物了吗？",
    "home.ctaSubtitle": "加入成千上万的满意客户",
    "home.browseCollection": "浏览系列",
    "shop.title": "所有产品",
    "shop.subtitle": "浏览我们的优质产品完整系列",
    "shop.search": "搜索产品...",
    "shop.allCategories": "所有类别",
    "shop.newest": "最新",
    "shop.priceLow": "价格：从低到高",
    "shop.priceHigh": "价格：从高到低",
    "shop.popular": "热门",
    "shop.highestRated": "最高评分",
    "shop.deals": "限时优惠",
    "shop.onSale": "促销中",
    "shop.inStock": "仅有库存",
    "shop.minRating": "最低评分",
    "shop.allRatings": "所有评分",
    "shop.priceRange": "价格范围",
    "shop.showing": "显示",
    "shop.of": "共",
    "shop.products": "产品",
    "shop.noProducts": "未找到产品",
    "shop.noProductsDesc": "尝试调整筛选条件",
    "contact.title": "联系我们",
    "contact.subtitle": "有问题？给我们发消息，我们会尽快回复。",
    "contact.sendMessage": "发送消息",
    "contact.messageSent": "消息已发送！",
    "contact.messageSentDesc": "感谢您的联系。我们会尽快回复。",
    "contact.name": "姓名",
    "contact.email": "电子邮件",
    "contact.subject": "主题",
    "contact.message": "消息",
    "contact.namePlaceholder": "您的姓名",
    "contact.emailPlaceholder": "your@email.com",
    "contact.subjectPlaceholder": "我们能如何帮助您？",
    "contact.messagePlaceholder": "告诉我们更多关于您的问题...",
    "contact.send": "发送消息",
    "contact.sending": "发送中...",
    "contact.emailUs": "发邮件",
    "contact.callUs": "致电我们",
    "contact.visitUs": "拜访我们",
    "contact.hours": "周日-周六: 9AM - 6PM",
    "cart.title": "购物车",
    "cart.empty": "购物车为空",
    "cart.emptyDesc": "看起来您还没有添加任何产品",
    "cart.browse": "浏览产品",
    "cart.clearAll": "清空全部",
    "cart.subtotal": "小计",
    "cart.shipping": "运费在结账时计算",
    "cart.checkout": "去结账",
    "cart.continueShopping": "继续购物",
    "cart.selectItems": "选择要支付的商品",
    "cart.selectAll": "全选",
    "cart.deselectAll": "取消全选",
    "cart.items": "件商品",
    "cart.selected": "已选择",
    "cart.continuePayment": "继续付款",
    "cart.backToCart": "返回购物车",
    "checkout.choosePayment": "选择支付方式",
    "checkout.selectCurrency": "选择支付货币",
    "checkout.currencyRequired": "请选择一种货币以继续",
    "checkout.fiatCurrency": "法定货币",
    "checkout.cryptocurrency": "加密货币",
    "checkout.bankTransfer": "银行转账",
    "checkout.bankTransferDesc": "直接银行存款",
    "checkout.cryptoDesc": "USDT (BEP20)",
    "checkout.stablecoin": "稳定币支付",
    "checkout.paymentDetails": "支付详情",
    "checkout.transactionRef": "交易参考号 / 哈希",
    "checkout.paymentDate": "支付日期",
    "checkout.senderName": "发送者姓名",
    "checkout.senderNamePlaceholder": "银行账户或钱包上的姓名",
    "checkout.additionalNotes": "附加说明（可选）",
    "checkout.notesPlaceholder": "关于您付款的其他信息...",
    "checkout.proofRequired": "支付凭证",
    "checkout.uploadProof": "点击上传支付凭证",
    "checkout.uploadFormats": "JPG、PNG、WebP 或 PDF（最大5MB）",
    "checkout.orderSummary": "订单摘要",
    "checkout.total": "总计",
    "checkout.submitOrder": "提交订单",
    "checkout.uploading": "上传中...",
    "checkout.processing": "处理订单中...",
    "checkout.submitting": "提交中...",
    "checkout.wait": "请等待我们处理您的订单...",
    "checkout.orderSubmitted": "订单已提交！",
    "checkout.orderPlaced": "已下单。",
    "checkout.verifyNotice": "付款验证后我们会通知您。",
    "checkout.goToDashboard": "前往面板",
    "checkout.viewOrder": "查看订单详情",
    "checkout.reversePurchase": "撤销购买（24小时内）",
    "footer.newsletter": "订阅我们的通讯",
    "footer.newsletterDesc": "获取独家优惠和新品提醒。",
    "footer.emailPlaceholder": "输入您的邮箱",
    "footer.subscribe": "订阅",
    "footer.subscribing": "订阅中...",
    "footer.quickLinks": "快速链接",
    "footer.customerService": "客户服务",
    "footer.contactUs": "联系我们",
    "footer.rights": "版权所有。",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.shippingPolicy": "配送政策",
    "footer.description": "您的时尚、电子产品和生活方式产品的高端目的地。",
    "general.all": "全部",
  },
};

export const languageNames: Record<Language, string> = {
  en: "English",
  fr: "Français",
  es: "Español",
  pt: "Português",
  zh: "中文",
};

export const languageFlags: Record<Language, string> = {
  en: "🇺🇸",
  fr: "🇫🇷",
  es: "🇪🇸",
  pt: "🇧🇷",
  zh: "🇨🇳",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("trendycart-language");
    return (stored as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("trendycart-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
